// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYsUCDHQZf1op5tfZyisryPmQhTQwFtzs',
    appId: '1:713764696012:web:d08a6912066a9a758ab769',
    messagingSenderId: '713764696012',
    projectId: 'mma3-efa0b',
    authDomain: 'mma3-efa0b.firebaseapp.com',
    storageBucket: 'mma3-efa0b.firebasestorage.app',
    measurementId: 'G-QHF5ETYPZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8BNfPlwDDJ3GdOeSbEVfh3Vw8W2gkPz0',
    appId: '1:713764696012:android:4b491d6f24a08b9b8ab769',
    messagingSenderId: '713764696012',
    projectId: 'mma3-efa0b',
    storageBucket: 'mma3-efa0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA86Dwf1s1Z_aW0mwH2paqVVGSdMgAHQd8',
    appId: '1:713764696012:ios:0efea02842e7f12b8ab769',
    messagingSenderId: '713764696012',
    projectId: 'mma3-efa0b',
    storageBucket: 'mma3-efa0b.firebasestorage.app',
    iosBundleId: 'com.example.maa3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA86Dwf1s1Z_aW0mwH2paqVVGSdMgAHQd8',
    appId: '1:713764696012:ios:0efea02842e7f12b8ab769',
    messagingSenderId: '713764696012',
    projectId: 'mma3-efa0b',
    storageBucket: 'mma3-efa0b.firebasestorage.app',
    iosBundleId: 'com.example.maa3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYsUCDHQZf1op5tfZyisryPmQhTQwFtzs',
    appId: '1:713764696012:web:84f00c06ac20e41e8ab769',
    messagingSenderId: '713764696012',
    projectId: 'mma3-efa0b',
    authDomain: 'mma3-efa0b.firebaseapp.com',
    storageBucket: 'mma3-efa0b.firebasestorage.app',
    measurementId: 'G-W403B8NHSN',
  );

}